server:
  port: 8081
spring:
  application:
    name: remark
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${remark.mysql.url}
    username: root
    password: ${remark.mysql.passwod}
  redis:
    host: ${remark.redis.host}
    port: 6379
    password: ${remark.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.remark.entity # 别名扫描包
logging:
  level:
    com.remark: debug

aliyun:
  sms:
    accessKey: ${remark.alibaba.sms.accessKey}
    accessSecret: ${remark.alibaba.sms.accessSercet}

redisson:
  url: ${ecs.redis.url}
  password: ${ecs.redis.password}