---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13759.
--- DateTime: 2024/7/30 17:39
---

--- 释放锁判断有没有自己的锁
if (redis.call(hexists,KEY[1],ARGV[1])==0) then
    --- 没有就返回
    return nil;
end;

--- 有就减减
local count = redis.call(hincrby,KEY[1],ARGV[1],'-1');
--- 判断是否小于0，小于则删除,大于就刷新
if (count>0) then
    redis.call(expire,KEY[1],ARGV[2])
    return nil;
else
    redis.call(del,KEY[1]);
    return nil;
end;

