---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 13759.
--- DateTime: 2024/8/20 13:57
---
-- 参数列表 优惠券id、用户id
local voucherId = ARGV[1]
local userId = ARGV[2]

--key列表 优惠券key、购买用户集合key
local voucherKey = "seckill:stock:" .. voucherId
local setKey = "seckill:order:" .. voucherId

--- 判断库存是否有剩
if (tonumber(redis.call('get', voucherKey)) <= 0) then
    return 1
end
--- 判断用户是否购买过
if (redis.call('sismember', setKey,userId) == 1) then
    return 2
end
-- 扣库存
redis.call('incrby',voucherKey,-1)
-- 下单
redis.call('sadd',setKey,userId)
return 0
